version: '3'
services:
  jupyter:
    restart: always
    build:
      context: .
      args:
        DOCKER_UID: ${DOCKER_UID}
        DOCKER_USER: ${DOCKER_USER}
        DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    container_name: 'polars_100_knocks'
    tty: true
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}
    volumes:
      - ./:/home/${DOCKER_USER}/work
